### ISSUE TITLE
Rename `unstable` tag to `stable`

### ISSUE THREAD

**Issue by andras-tim** [linuxserver/docker-unifi#59]
I want to change current `unstable` tag to `stable` because of the version **5.7** is absolute stable (but not **LTS** as **5.6**).
Please, check this out: [UniFi - Current Controller Versions](https://help.ubnt.com/hc/en-us/articles/115000441548-UniFi-Current-Controller-Versions)

**Comment by sudoforge** [comment]
I'd approach this a different way.

It seems like the `master` branch tracks LTS releases, while the `unstable` branch tracks Stable releases, and no tracking is performed for release candidates or development builds.

I think that makes the usage of this image a little funky. I'd like to see:

- `master` track the latest Stable release (and publish to the registry with the `latest` tag)
- `lts` track the latest LTS releases (and publish to the registry with the `lts` tag)

This way, users get the latest Stable image, while those consumers who want or need the LTS version can still do that.

References:

- https://www.ubnt.com/download/unifi/
- https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-6-37-LTS-Stable-has-been-released/ba-p/2318810
- https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-7-23-Stable-has-been-released/ba-p/2318813

**Comment by ssbarnea** [comment]
Voting for matching Ubiquity naming convention for versions as I find the current docker tags really confusing.

I do want to use the last stable (non testing) version and stick to this. Now I am forced to configure the tag "unstable" which is clearly illogic. So "unstable" means "stage",... what can I say.

**Comment by sparklyballs** [comment]
in our experience the 5.7x branch is anything but stable with a 100% failure rate amongst the team

you can update any branch regardless of tag @sudoforge but given that 5.7 is an upbreak and there is no easy downgrade path beyond wiping all existing data and readopting the controllers etc, for the time being 5.7 is regarded unstable by us

**Comment by sparklyballs** [comment]
the readme clearly states that the unstable branch is [5.7x](https://github.com/linuxserver/docker-unifi#tags) and you should always read the instructions

**Comment by sparklyballs** [comment]
also it should be noted that the rollback was not as simple as deleting persistent data and using a backup

in my personal case the upbreak killed my wifi completely and sent my controller into a seemingly unending adopting loop, because of botched firmware with the initial 5.7 release

and there were pages of people on the ubiquiti forum with similar stories as well as within our team

it was felt that giving 5.7x a different label was the better option, rather than the lottery of breaking other user's perfectly working setups and how hard is it to add a tab ? after it all the suggestion of a tag for lts amounts to the same thing but in reverse

**Comment by andras-tim** [comment]
I think this is an enough-complex stuff for anyone do a backup before upgrade/downgrade this stuff...

And if the Ubnt thinks, the 5.7 is stable but it is not, this will shame on Ubnt.

**Comment by dam09fr** [comment]
And 5.8.x will be out soon ...
https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-8-21-Stable-Candidate-has-been-released/ba-p/2380042

**Comment by beanstown106** [comment]
ya the naming here is definitely confusing, i just setup my first ubiquiti network and since i run unraid as my home server i figured i would install the linuxserver version of unify but after doing some research it seems that its not up to date. from reading here it looks like you guys are renaming ubiquitis lts to stable, and ubiquitis stable to testing?

is it as simple as pointing to the testing branch when using unraid to get ubiquitis stable?

**Comment by sudoforge** [comment]
@beanstown106 Yes, you could do that, or alternatively use a different author's image I linked to in [an earlier comment][0], which follows a more standing tagging scheme.

**Comment by tobbenb** [comment]
@beanstown106 We are on the latest release on the download page. As said earlier, we do not build any images with unifi versions released on their blog.

We are not going to change the tags as it breaks things for others. Also the tags are just tags. One should read the Readme before running a container. The tags are clearly explained there.

**Comment by Magic815** [comment]
How do you all plan to handle the tag naming now that Ubnt is calling 5.8.x releases 'stable' ?
https://community.ubnt.com/t5/UniFi-Routing-Switching/UniFi-Controller-Releases-Updated-Jun-27th-2018/m-p/2400866

Is your plan to update the docker so that the 'unstable' tag will now just reference 5.8.x? Or are you planning to revisit the tag naming?

**Comment by sudoforge** [comment]
@Magic815 It doesn't sound like the authors of this project will be revisiting their tag naming scheme to match that of Ubiquiti's.

**Comment by CHBMB** [comment]
No, we're not.  Shakespeare once said "A rose by any other name would smell as sweet"

Quite frankly this conversation has got tiresome, people keep asking for the tag name to change from unstable to stable and it achieves absolutely nothing.  

In our experience "stable" from Unifi is not always that stable and as a group we don't feel able to label it as such when several of the linuxserver members have been burnt in the past using so called stable releases.  

The LTS branch will be the default supported branch and what Unifi choose to call stable will remain our unstable branch, as it seems the most fitting description.

One other consideration is for the people using the container that are quite happy running along with 5.6/LTS release, and we feel changing the labelling scheme is confusing for those people and potentially cause them to lose the stability that they are used to, by acting as far as I'm concerned as glorified beta testers.

I'm closing this issue, as further discussion is not helpful.

**Comment by Magic815** [comment]
Fine by me. But please don't confuse my question for a complaint. My scenario (as detailed further in the LimeTech thread) is just causing me to want to confirm that 'unstable' will eventually point to 5.8.x. It sounds like that answer is yes?

**Comment by andras-tim** [comment]
Dear @CHBMB,

At first, what LTS is

- LTS = Long Term Supported (so this will doesn't have fewer bugs), but the most of the bug fixes will be backported.
- And if you have used any software, you can know, the LTS can contain bugs too
- The main difference between the **LTS Stable** and the **Stable** is the upgrade cost. The LTS doesn't have non-reversible changes.
- The Ubuntu is an excellent example for what the LTS is.

So, I can't understand why you are obdurate. Are you smarter than Ubnt developers? Do you think the Ubnt wants to lie about bugs or stability?

**Comment by beanstown106** [comment]
I got an idea why not just name the branches for what they are 5.6 5.7 and 5.8 and leave 5.6 set as default that way users who want to run 5.7 can do :5.7 and users who want to run 5.8 can do :5.8

**Comment by CHBMB** [comment]
@andras-tim Look, this whole thread is going round in circles over two letters `un` at some point we'll possibly look at the branch names and quite frankly @beanstown106 has come up with a reasonable suggestion.

But with all due respect, we have a ton of other stuff going on at the moment with our backend and this is pretty low on our list of priorities.

Do I think I'm smarter than the Ubnt developers, maybe not as far as their software is concerned, but pretty sure I'm smarter than them in regards to my day job.

Do I think Ubnt want to lie?  No, but I've been using their software long enough and have be burnt several times in the past with their definition of stable which as far as I can tell is pretty fucking wide of the mark compared to the accepted definition of stable.  Stable software should not be hosing installs.

I'm well aware of the definition of LTS thank you and am very familiar with Ubuntu, your condescension is noted.

It's very easy for you to stand from the sidelines and complain about our naming convention, but it's not you that has to support this stuff.  Remember we're volunteers, and our free time is limited.  That also means we actually have zero obligations as well and quite honestly the Ubnt stuff takes up a disproportionate amount of our limited time.

Now for the final time, please consider this topic closed for now.

**Comment by sudoforge** [comment]
> I'm closing this issue, as further discussion is not helpful.

> Now for the final time, please consider this topic closed for now.

Might I suggest that you (or another organization member who can) simply locks the issue?

**Comment by CHBMB** [comment]
@sudoforge I considered it, but it felt more dictatorial than I was comfortable with, despite what you might think from this thread, I'm actually a pretty nice guy, and it's not really my style to just shut stuff down.

But as is often the case, there's more going on than people are aware of and I'd rather obtain understanding and a "peaceful resolution"

If it continues to be a problem then I will indeed lock the thread.

**Comment by CHBMB** [comment]
We're actually looking at a complete overhaul of the backend of our container production in general and it makes no sense from our point of view to make any changes now.  I probably didn't make that clear enough, and we have talked about this container internally.

Truth be told, the attitude some people have given us from various sources, not just github, has pretty much annoyed all of the ls.io members, we feel that people are only seeing their current perspective with no knowledge of other considerations.  Any change we make we have to consider the overall user base, not just those that are active here, there's far more people who don't monitor these things.

We had a container that was based solely on the LTS branch, and then we made another branch due to demand for 5.7, at the time this was built 5.7 was anything but stable and there was a long thread on the Ubnt forums as testament to this, and we tagged it unstable accordingly.  This was after both mine and @sparklyballs install got trashed by 5.7.

If you want to run v5.7 whatever we name it, feel free, but have a little insight into when we released this we had a hell of a job supporting people who had issues with what was supposedly a stable release, and please bear in mind that there are support considerations we have to make.

With that being said, if anyone wants to get involved then feel free, if you want to dedicate some time to help out, feel free, hit us up on Discord and have a chat.

If you don't have enough free time to help out, that's fine, but realise that our free time is a valuable, finite resource, and time we spend on linuxserver is time we're not spending with our wives and children.

**Comment by IcyMidnight** [comment]
Was just about to post a proposal in a new issue, but I found this thread so I'll post here instead. I realise that this issue is considered closed but I was bitten by the confusing naming in the README -- I even created https://github.com/linuxserver/docker-unifi/pull/84 to try to clear it up, but after finding this thread I think my update may actually (still) be misleading.

My reading of the README suggested that the two branches in this repo were meant to track the two UniFi release streams: master->LTS, unstable->Unstable.

Would it be possible to create a third branch/tag to clear up confusion? I.e.
master->LTS
stable->Stable
unstable->Unstable

At the very least it might be worth being explicit about which UniFi tracks each branch is tracking, with a note about past experience with the stable branch, e.g.
### **Tags:**
- **linuxserver/unifi** - the LTS Stable Unifi branch.
- **linuxserver/unifi:stable** - the Stable UniFi branch.
_Warning_: previous experience with UniFi's "Stable" branch have shown it to be anything but reliably stable. Please use this tag with that understanding, at your own risk.
- **linuxserver/unifi:unstable** - the Unstable UniFi branch.
Presumably even less stable than "Stable".

I'm not sure what work needs to occur in the backend - I assume there is some since the git commits for revving the version seem to be just small string changes - but if it's approachable by someone new to the linuxserver.io infrastructure, I'd be willing to put some time in to get it set it up for three tags.

**Comment by ssbarnea** [comment]
Those guys at unifi... how hard is to use `master` (or `latest` as image tag), `stable` and `lts` which is as simple, standard and does not need you to read docs/articles about their unique approach regarding branch naming.

PS. Please stay simple, lowercase. Next step after introducing the uppercase would be to create the über tag or some emoji ;)
